version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
commands:
  install_frontend:
    description: "command for frontend Installation"
    steps:
      # install and cache dependencies
      - restore_cache:
          keys:
            # creating caching using checksum
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Install frontend Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  install_backend:
    description: "command for backend installation"
    steps:          
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install backend Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run api:install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:16.18"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '16.18' 
      - checkout
      - install_frontend
      - install_backend   
      - run:
          name: Front-End Lint
          command: npm run frontend:lint
      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: npm run frontend:build
      # TODO: Build the backend API      
      - run:
          name: API Build
          command: npm run api:build
  test:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '16.18' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - install_frontend
      - install_backend
      - run: 
          name: Test Frontend 
          command: |
            npm run frontend:test
            npm run frontend:e2e
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '16.18' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - install_frontend
      - install_backend
      # - run:
      #     name: Deploy Frontend
      #     command: npm run frontend:deploy
      # - run:
      #     name: Deploy Backend
      #     command: npm run api:deploy
      - run:
          name: Deploy APP
          command: npm run deploy
            
workflows:
  udagram:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
